# trace_anything/configs/eval.yaml

hydra:
  run:
    dir: .        
  job:
    chdir: false
  output_subdir: null
  job_logging:
    disable_existing_loggers: true
    root:
      handlers: []
    handlers: {}
  verbose: false

ckpt_path: checkpoints/trace_anything.ckpt

model:
  _target_: fast3r.models.multiview_dust3r_module.MultiViewDUSt3RLitModule

  net:
    _target_: fast3r.models.fast3r.Fast3R
    encoder_args:
      encoder_type: croco
      img_size: 512
      patch_size: 16
      patch_embed_cls: ManyAR_PatchEmbed
      embed_dim: 1024
      num_heads: 16
      depth: 24
      mlp_ratio: 4
      pos_embed: RoPE100
      attn_implementation: flash_attention
    decoder_args:
      decoder_type: fast3r
      random_image_idx_embedding: false
      enc_embed_dim: 1024
      embed_dim: 1024
      num_heads: 16
      depth: 24
      mlp_ratio: 4.0
      qkv_bias: true
      drop: 0.0
      attn_drop: 0.0
      attn_implementation: flash_attention
    head_args:
      head_type: dpt
      output_mode: pts3d
      landscape_only: true
      depth_mode: [exp, -.inf, .inf]
      conf_mode: [exp, 1, .inf]
      patch_size: 16
      with_local_head: true
    freeze: none
    targeting_mechanism: bspline_conf   
    poly_degree: 10

  train_criterion:
    _target_: fast3r.dust3r.losses.ConfLossMultiviewV2
    pixel_loss:
      _target_: fast3r.dust3r.losses.Regr3DMultiviewV3
      criterion:
        _target_: fast3r.dust3r.losses.L21Loss
      norm_mode: avg_dis
    alpha: 0.2

  validation_criterion:
    _target_: fast3r.dust3r.losses.ConfLossMultiviewV2
    pixel_loss:
      _target_: fast3r.dust3r.losses.Regr3DMultiviewV3
      criterion:
        _target_: fast3r.dust3r.losses.L21Loss
      norm_mode: avg_dis
    alpha: 0.2

  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 1.0e-4
    betas: [0.9, 0.95]
    weight_decay: 0.05

  scheduler:
    _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    _partial_: true
    warmup_epochs: 1
    max_epochs: 10
    eta_min: 1.0e-6

  compile: false
